use std::{env, fs, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=material_ids.txt");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let ids_path = manifest_dir.join("material_ids.txt");
    let raw = fs::read_to_string(&ids_path).expect("read material_ids.txt");

    let mut entries = Vec::new();
    for (line_no, line) in raw.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let (name, value) = line
            .split_once('=')
            .unwrap_or_else(|| panic!("invalid material id definition on line {}", line_no + 1));
        let name = name.trim();
        let value: u16 = value
            .trim()
            .parse()
            .unwrap_or_else(|_| panic!("invalid numeric ID on line {}", line_no + 1));

        assert!(
            name.chars()
                .all(|c| c.is_ascii_uppercase() || c == '_' || c.is_ascii_digit()),
            "material ID names must be SCREAMING_SNAKE_CASE; line {}",
            line_no + 1
        );

        entries.push((name.to_owned(), value));
    }

    let mut rust_out = String::from("// @generated by build.rs from material_ids.txt.\n");
    rust_out.push_str("use crate::world::MaterialId;\n\n");
    for (name, value) in &entries {
        rust_out.push_str(&format!("pub const {}: MaterialId = {};\n", name, value));
    }

    rust_out.push_str("\npub const GENERATED_MATERIAL_IDS: &[(&str, MaterialId)] = &[\n");
    for (name, value) in &entries {
        rust_out.push_str(&format!("    (\"{}\", {}),\n", name, value));
    }
    rust_out.push_str("];\n");

    let mut wgsl_out = String::from("// @generated by build.rs from material_ids.txt.\n");
    wgsl_out.push_str("const EMPTY: u32 = 0u;\n");
    for (name, value) in &entries {
        wgsl_out.push_str(&format!("const {}: u32 = {}u;\n", name, value));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    fs::write(out_dir.join("material_ids.rs"), rust_out).expect("write generated rust ids");
    fs::write(out_dir.join("material_ids.wgsl"), wgsl_out).expect("write generated wgsl ids");
}
