use std::{env, fs, path::PathBuf};

const MATERIAL_IDS: &[(&str, u16)] = &[
    ("EMPTY", 0),
    ("STONE", 1),
    ("WOOD", 2),
    ("SAND", 3),
    ("SNOW", 4),
    ("WATER", 5),
    ("LAVA", 6),
    ("ACID", 7),
    ("SMOKE", 8),
    ("STEAM", 9),
    ("STEEL", 10),
    ("FIRE_GAS", 11),
    ("TORCH", 12),
    ("EMBER_HOT", 13),
    ("EMBER_WARM", 14),
    ("EMBER_ASH", 15),
    ("DIRT", 16),
    ("TURF", 17),
    ("BUSH", 18),
    ("GRASS", 19),
    ("PLANT", 20),
    ("WEED", 21),
    ("TREE_SEED", 22),
    ("LEAVES", 23),
    ("DEAD_LEAF", 24),
];

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    write_rust_constants(&out_dir);
    write_wgsl_constants(&out_dir);
}

fn write_rust_constants(out_dir: &PathBuf) {
    let mut out = String::from("// @generated by build.rs\n");
    out.push_str("pub const MATERIAL_IDS: [MaterialId; 25] = [\n");
    for (_, id) in MATERIAL_IDS {
        out.push_str(&format!("    {id},\n"));
    }
    out.push_str("];\n\n");

    for (name, id) in MATERIAL_IDS {
        out.push_str(&format!("pub const {name}: MaterialId = {id};\n"));
    }

    fs::write(out_dir.join("sim_ids.rs"), out).expect("failed to write sim_ids.rs");
}

fn write_wgsl_constants(out_dir: &PathBuf) {
    let mut out = String::from("// @generated by build.rs\n");
    for (name, id) in MATERIAL_IDS {
        out.push_str(&format!("const {name}: u32 = {id}u;\n"));
    }
    out.push('\n');

    fs::write(out_dir.join("sim_ids.wgsl"), out).expect("failed to write sim_ids.wgsl");
}
